version: '2'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  power-outage-monitor:
    restart: always
    image: ccfs/power-outage-monitor
    networks:
     - nginx-proxy
    environment:
     - VIRTUAL_HOST=power-api.quokka.ninja
    volumes:
     - ./power-outage-monitor/sites:/app/sites
networks:
  nginx-proxy:
    external:
      name: nginx-proxy
