version: '2'
services:
  power-outage-monitor:
    restart: always
    image: ccfs/power-outage-monitor
    labels:
      com.centurylinklabs.watchtower.enable: true
      caddy: http://power-api.quokka.ninja
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
     - caddy
    volumes:
     - ./power-outage-monitor/sites:/app/sites
networks:
  caddy:
    external: true
