version: '3.8'
services:
  adarca:
    image: ccfs/contextual-cybernation
    build: .
    labels:
      caddy: power-api.quokka.ninja
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
     - caddy
networks:
  caddy:
    external: true
