version: '2'
services:
  pom:
    restart: always
    image: ccfs/contextual-cybernation
    build: .
    labels:
      caddy: power-api.quokka.ninja
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
     - caddy
networks:
  caddy:
    external: true
