version: '2'
services:
  power-outage-monitor:
    restart: always
    image: ccfs/power-outage-monitor
    labels:
      # enable for docker and watchtower workflow
      # com.centurylinklabs.watchtower.enable: true
      # edit to correct hostname
      caddy: api.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
     - caddy
    volumes:
     - ./power-outage-monitor/sites:/app/sites
networks:
  caddy:
    external: true
